# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6384e67d72c35b2fa690dde55f8ec223842acc1aa3ed7cb9241341fc3f6cf4284d851b1b9bd765d1a918d332ca6158106b95567876fb55660d9bd8a216d9dbe8

test:
  secret_key_base: ff5a73784b49c63ef9223a1be0b5425cbe1f332e525240fa36637421499cd633e2fd2e6b3fe56e7bad94e736f2971bee716eb40ff5de1f1ec5de89e1d76193cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
